apiVersion: "apps/v1"
kind: "List"
items:
  - apiVersion: "extensions/v1beta1"
    kind: "Deployment"
    metadata:
      annotations:
        fabric8.io/git-commit: "78bd65851c7d9e22652957107fc339a55f80b606"
        fabric8.io/git-branch: "release-v0.1.5"
        fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=zipkin&var-version=0.1.5"
        fabric8.io/build-id: "3"
        fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/78bd65851c7d9e22652957107fc339a55f80b606"
        fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/3"
      labels:
        provider: "fabric8"
        project: "zipkin"
        version: "0.1.5"
        group: "io.fabric8.zipkin"
      name: "zipkin"
    spec:
      replicas: 1
      selector:
        matchLabels:
          provider: "fabric8"
          project: "zipkin"
          group: "io.fabric8.zipkin"
      template:
        metadata:
          annotations:
            fabric8.io/git-commit: "78bd65851c7d9e22652957107fc339a55f80b606"
            fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=zipkin&var-version=0.1.5"
            fabric8.io/build-id: "3"
            fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/3"
            fabric8.io/git-branch: "release-v0.1.5"
            fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/78bd65851c7d9e22652957107fc339a55f80b606"
          labels:
            provider: "fabric8"
            project: "zipkin"
            version: "0.1.5"
            group: "io.fabric8.zipkin"
        spec:
          containers:
            - env:
                - name: "STORAGE_PORT_9042_TCP_ADDR"
                  value: "cassandra.svc.cluster.local:9042"
                - name: "STORAGE_TYPE"
                  value: "cassandra3"
                - name: "TRANSPORT_TYPE"
                  value: "http"
                - name: "CASSANDRA_CONTACT_POINTS"
                  value: "cassandra.svc.cluster.local"
                - name: "CASSANDRA_USERNAME"
                  value: "cassandra"
                - name: "CASSANDRA_PASSWORD"
                  value: "cassandra"
                - name: "KUBERNETES_NAMESPACE"
                  valueFrom:
                    fieldRef:
                      fieldPath: "metadata.namespace"
              image: "openzipkin/zipkin:1.13.0"
              name: "zipkin"
              readinessProbe:
                httpGet:
                  path: "/api/v1/services"
                  port: 9411
                initialDelaySeconds: 5
              resources:
                limits:
                  cpu: "0"
                  memory: "0"
                requests:
                  cpu: "0"
                  memory: "0"
  - apiVersion: "extensions/v1beta1"
    kind: "Deployment"
    metadata:
      annotations:
        fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/zookeeper/src/main/fabric8/icon.png"
        fabric8.io/git-commit: "500219733b1151415686940f4b893d7add206822"
        fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=zookeeper&var-version=2.2.153"
        fabric8.io/build-id: "2"
        fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/2"
        fabric8.io/git-branch: "release-v2.2.153"
        fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/500219733b1151415686940f4b893d7add206822"
      labels:
        provider: "fabric8"
        project: "zookeeper"
        version: "2.2.153"
        group: "io.fabric8.ipaas.apps"
        serverId: "1"
      name: "zookeeper"
    spec:
      replicas: 1
      selector:
        matchLabels:
          provider: "fabric8"
          project: "zookeeper"
          group: "io.fabric8.ipaas.apps"
      template:
        metadata:
          annotations:
            fabric8.io/git-commit: "500219733b1151415686940f4b893d7add206822"
            fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=zookeeper&var-version=2.2.153"
            fabric8.io/build-id: "2"
            fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/2"
            fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/zookeeper/src/main/fabric8/icon.png"
            fabric8.io/git-branch: "release-v2.2.153"
            fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/500219733b1151415686940f4b893d7add206822"
          labels:
            provider: "fabric8"
            project: "zookeeper"
            version: "2.2.153"
            group: "io.fabric8.ipaas.apps"
        spec:
          containers:
            - env:
                - name: "ENSEMBLE_SIZE"
                  value: "1"
                - name: "KUBERNETES_NAMESPACE"
                  valueFrom:
                    fieldRef:
                      fieldPath: "metadata.namespace"
              image: "fabric8/zookeeper:2.2.153"
              imagePullPolicy: "IfNotPresent"
              name: "zookeeper"
              ports:
                - containerPort: 2181
                  name: "zkclient"
                - containerPort: 8778
                  name: "jolokia"
              resources:
                limits:
                  cpu: "0"
                  memory: "0"
                requests:
                  cpu: "0"
                  memory: "0"
              securityContext:
                privileged: false
              volumeMounts:
                - mountPath: "/opt/zookeeper/data"
                  name: "data"
                  readOnly: false
                - mountPath: "/opt/zookeeper/log"
                  name: "log"
                  readOnly: false
          volumes:
            - emptyDir:
                medium: "Memory"
              name: "data"
            - emptyDir:
                medium: "Memory"
              name: "log"
