server:
  port: 9411

spring:
  application:
    name: zipkin-server
  datasource:
    schema: classpath:/cassandra3-schema.cql
    url: jdbc:cassandra://127.0.0.1:9042
    keyspace: zipkin3
    contactPoints: localhost
    initialize-mode: true
    continue-on-error: true
  sleuth:
    enabled: false
    preferIpAddress: true

  main:
    allow-bean-definition-overriding: true
management:
  metrics:
    web:
      server:
        auto-time-requests: false

zipkin:
  storage:
      type: cassandra3

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${customer.discovery.port}/eureka/ # using eureka instead of localhost
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
    preferIpAddress: true



